server:
  port: 7000

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver-class-name: org.postgresql.Driver
    username: jelly
    password: jelly
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
